# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  test_db:
    image: postgres:12.2-alpine
    command: postgres -c log_statement=all
    ports:
      - "41101:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth_db
    logging:
      options:
        max-size: 500m
  db:
    image: postgres:12.2-alpine
    ports:
      - "41001:5432"
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth_db
    logging:
      options:
        max-size: 500m
  web:
    image: auth_api
    build: .
    command: gunicorn -b 0.0.0.0:5000 auth_api.wsgi:app
    env_file:
      - .flaskenv
    volumes:
      - ./auth_api:/code/auth_api
      - ./migrations:/code/migrations
    ports:
      - "41002:5000"
    logging:
      options:
        max-size: 500m
    depends_on:
      - db
