"""empty message

Revision ID: d516befe650b
Revises: 3c403aee5d08
Create Date: 2020-03-01 16:54:00.927520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd516befe650b'
down_revision = '3c403aee5d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'user', ['external_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'external_uuid')
    # ### end Alembic commands ###
