"""divide user entities into sub entities

Revision ID: 04cf675dc53e
Revises: adb8d84fee4e
Create Date: 2020-05-09 16:07:41.585713+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cf675dc53e'
down_revision = 'adb8d84fee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=80), nullable=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('family_name', sa.Text(), nullable=True),
        sa.Column('given_name', sa.Text(), nullable=True),
        sa.Column('picture', sa.Text(), nullable=True),
        sa.Column('google_user_id', sa.String(length=80), nullable=False),
        sa.Column('locale', sa.String(length=80), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('google_user_id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_table('internal_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('login', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=80), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('login'),
        sa.UniqueConstraint('user_id')
    )

    op.execute('insert into internal_user (login, email, password) ' +
               'select username, email, password from "user"')

    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=80), nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])

    op.execute('update "user" set password=iu.password, email=iu.email ' +
               'from internal_user iu where "user".id = iu.user_id')

    op.alter_column('user', 'password', nullable=True)
    op.alter_column('user', 'email', nullable=True)

    op.drop_table('internal_user')
    op.drop_table('google_user')
    # ### end Alembic commands ###
