"""empty message

Revision ID: adb8d84fee4e
Revises: 5658753ce8cb
Create Date: 2020-03-16 19:04:20.231738+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'adb8d84fee4e'
down_revision = '5658753ce8cb'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE user_role_enum ADD VALUE 'tech'")
    op.add_column('user', sa.Column('resources', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resources')
    # ### end Alembic commands ###
