# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth_db
    logging:
      options:
        max-size: 500m
  lint:
    image: auth_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: pylint auth_api --rcfile=pylintrc 2>&1 | tee pylint.txt
    volumes:
      - reports/pylint.txt:/code/pylint.txt
  migration:
    image: auth_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; auth_api db upgrade'
    env_file:
      - .flaskenv
    depends_on:
      - db
  tests:
    image: auth_api
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pytest --html test-report.html tests'
    env_file:
      - .flaskenv
    volumes:
      - reports/test-report.html:/code/test-report.html
    depends_on:
      - migration
