# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth_db
    logging:
      options:
        max-size: 500m
  lint:
    image: auth_api
    build: .
    command: pylint auth_api --rcfile=pylintrc
  migration:
    image: auth_api
    build: .
    command: auth_api db upgrade
    env_file:
      - .flaskenv
    depends_on:
      - db
  tests:
    image: auth_api
    command: pytest tests
    env_file:
      - .flaskenv
    depends_on:
      - migration
