# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: auth_db
    logging:
      options:
        max-size: 500m
  web:
    image: auth_api
    build: ../backend/auth_service
    command: /code/run_tests.sh
    env_file:
      - .flaskenv
    volumes:
      - ../auth_api:/code/auth_api
      - ../migrations:/code/migrations
      - ../tests:/code/tests
      - ./run_tests.sh:/code/run_tests.sh
      - ./test_requirements.txt:/code/test_requirements.txt
      - ./pylintrc:/code/pylintrc
    depends_on:
      - db
