name: Test workflow

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Build base image
      run: docker build -t 'auth-service-base-img' .
    - name: Run linters
      run: docker-compose -f ci/docker-compose.yml run lint 
    - name: Migrate test db
      run: docker-compose -f ci/docker-compose.yml run migration
    - name: Run tests
      run: docker-compose -f ci/docker-compose.yml run tests
    - uses: actions/upload-artifact@v1
      with:
        name: check_results
        path: ci/reports
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: master