name: Test workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: docker build -t 'auth-service-base-img' .
    - name: Build check image
      run: docker build -t 'auth-service-check-img' -f ci/Dockerfile .
    - name: Run linters
      run: docker-compose -f ci/docker-compose.yml lint 
    - name: Migrate test db
      run: docker-compose -f ci/docker-compose.yml migration
    - name: Run tests
      run: docker-compose -f ci/docker-compose.yml tests
