name: CI Auth Service -2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world 2!
    - name: Run linters and tests
      run: docker-compose -f ci/docker-compose.yml run web
