name: Deploy image

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: de1m0s/little-diary-auth-service
        auto_tag: true
    - name: Send event to deploy service
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: de1mos242/little-diary-root
        event-type: auth-service-released
        client-payload: '{"version": "${GITHUB_REF:11}"}'
